Nvd.lab5.1/Models/NvdMember.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Nvd.lab5._1.Models
{
    public class NvdMember
    {
        [Required(ErrorMessage = "Hãy nhập mã số")]

        [DataType(DataType.Currency)]

        public int Id { get; set; }

        [Required(ErrorMessage = "Hãy nhập tên đăng nhập")]

        public string Username { get; set; }

        [Required(ErrorMessage = "Hãy nhập họ và tên")]

        public string FullName { get; set; }

        [Required(ErrorMessage = "Hãy nhập mật khẩu")]

        [DataType(DataType.Password)]

        public string Password { get; set; }

        [Required(ErrorMessage = "Hãy nhập tuổi")]

        [Range(18, 50, ErrorMessage = "Tuổi từ 18-50")]

        public int Age { get; set; }

        [Required(ErrorMessage = "Hãy nhập email")]

        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Email phải đúng định dạng")]

        public string Email { get; set; }
    }
}

Nvd.lab5.1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nvd.lab5._1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Nvd.lab5.1/Controllers/NvdMemberController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nvd.lab5._1.Models;

namespace Nvd.lab5._1.Controllers
{
    public class NvdMemberController : Controller
    {
        // GET: /NvdMember/CreateOne

        public ActionResult CreateOne()

        {

            return View();

        }

        //POST: /NvdMember/CreateOne

        [HttpPost]

        public ActionResult CreateOne(Member m)

        {

            //chuyển dữ liệu nhận được tới View Details

            return View("Details", m);

        }

        //GET: /NvdMember/CreateTwo

        public ActionResult CreateTwo()

        {

            return View();

        }

        //POST: /NvdMember/CreateTwo

        [HttpPost]

        public ActionResult CreateTwo(NvdMember m)

        {

            //kiểm tra trống các trường và thông báo lỗi tới VIEW

            if (m.Id == null)

            {

                ViewBag.error = "Hãy nhập mã số";

                return View();

            }

            if (m.Username == null)

            {

                ViewBag.error = "Hãy nhập tên đăng nhập";

                return View();

            }

            if (m.FullName == null)

            {

                ViewBag.error = "Hãy nhập tên họ và tên";

                return View();

            }

            if (m.Age == null)

            {

                ViewBag.error = "Hãy nhập tuổi";

                return View();

            }

            if (m.Email == null)

            {

                ViewBag.error = "Hãy nhập Email";

                return View();

            }

            //mẫu kiểm tra Email

            string regexPattern = @"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}";

            if (!System.Text.RegularExpressions.Regex.IsMatch(m.Email, regexPattern))

            {

                ViewBag.error = "Hãy nhập đúng định dạng";

                return View();

            }

            //nếu không xảy ra lỗi thì chuyển dữ liệu tới View Details

            return View("Details", m);

        }

        //GET: /NvdMember/CreateThree

        public ActionResult CreateThree()

        {

            return View();

        }

        //POST: /NvdMember/CreateThree

        [HttpPost]

        public ActionResult CreateThree(Member m)

        {

            //nếu trạng thái dữ liệu của Model hợp lệ thì chuyển dữ liệu tới View Details

            if (ModelState.IsValid)

                return View("Details", m);

            else

                return View(); //quay lại view Three để báo lỗi

        }

        //GET: /NvdMember/Details

        public ActionResult Details()

        {

            return View();

        }
    }
}

Nvd.lab5.1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Nvd.lab5.1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Nvd.lab5.1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Nvd.lab5.1/Views/NvdMember/CreateOne.cshtml
@model Nvd.lab5._1.Models.NvdMember

@{

    ViewBag.Title = "Sử dụng HTML validate data";

}

@using (Html.BeginForm())

{

    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <h2>Thêm thành viên</h2>

        <hr />

        <div class="form-group">

            @Html.Label("Mã thành viên", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.TextBoxFor(model => model.Id, new { Required = "Required", type = "number" })

            </div>

        </div>

        <div class="form-group">

            @Html.Label("Tên đăng nhập", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.TextBoxFor(model => model.Username, new { Required = "Required" })

            </div>

        </div>

        <div class="form-group">

            @Html.Label("Họ và tên", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.TextBoxFor(model => model.FullName, new { Required = "Required" })

            </div>

        </div>

        <div class="form-group">

            @Html.Label("Mật khẩu", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.PasswordFor(model => model.Password, new { Required = "Required" })

            </div>

        </div>

        <div class="form-group">

            @Html.Label("Tuổi", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.TextBoxFor(model => model.Age, new { Required = "Required", type = "number", min = "18", max = "60" })

            </div>

        </div>



        <div class="form-group">

            @Html.Label("Email", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.TextBoxFor(model => model.Email, new { Required = "Required", type = "email" })

            </div>

        </div>

        <div class="form-group">

            <div class="col-md-offset-2 col-md-10">

                <input type="submit" value=" Lưu " class="btn btn-default" />

            </div>

        </div>

    </div>

}

Nvd.lab5.1/Views/NvdMember/CreateThree.cshtml
@model Nvd.lab5._1.Models.NvdMember
@{

    ViewBag.Title = "Kiểm tra dữ liệu theo cách 3";

}

<h2>Kiểm tra dữ liệu theo cách 3</h2>

@using (Html.BeginForm())

{

    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true)

        <div class="form-group">

            @Html.Label("Mã thành viên", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.EditorFor(model => model.Id)

                @Html.ValidationMessageFor(model => model.Id)

            </div>

        </div>

        <div class="form-group">

            @Html.Label("Tên đăng nhập", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.EditorFor(model => model.Username)

                @Html.ValidationMessageFor(model => model.Username)

            </div>

        </div>

        <div class="form-group">

            @Html.Label("Họ và tên", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.EditorFor(model => model.FullName)

                @Html.ValidationMessageFor(model => model.FullName)

            </div>

        </div>

        <div class="form-group">

            @Html.Label("Mật khẩu", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.EditorFor(model => model.Password)

                @Html.ValidationMessageFor(model => model.Password)

            </div>

        </div>

        <div class="form-group">

            @Html.Label("Tuổi", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.EditorFor(model => model.Age)

                @Html.ValidationMessageFor(model => model.Age)

            </div>

        </div>

        <div class="form-group">

            @Html.Label("Email", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.EditorFor(model => model.Email)

                @Html.ValidationMessageFor(model => model.Email)

            </div>

        </div>

        <div class="form-group">

            <div class="col-md-offset-2 col-md-10">

                <input type="submit" value=" Lưu " class="btn btn-default" />

            </div>

        </div>

    </div>

}

Nvd.lab5.1/Views/NvdMember/CreateTwo.cshtml
@model Nvd.lab5._1.Models.NvdMember

@{

    ViewBag.Title = "Kiểm tra dữ liệu theo cách 2";

}

<h2>Kiểm tra dữ liệu theo cách 2</h2>

@if (ViewBag.error != null)

{

    <div class="alert alert-danger">@ViewBag.error</div>

}

@using (Html.BeginForm())

{

    @Html.AntiForgeryToken()



    <div class="form-horizontal">

        <hr />

        <div class="form-group">

            @Html.Label("Mã thành viên", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.EditorFor(model => model.Id)

            </div>

        </div>

        <div class="form-group">

            @Html.Label("Tên đăng nhập", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.EditorFor(model => model.Username)

            </div>

        </div>

        <div class="form-group">

            @Html.Label("Họ và tên", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.EditorFor(model => model.FullName)

            </div>

        </div>

        <div class="form-group">

            @Html.Label("Mật khẩu", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.PasswordFor(model => model.Password)

            </div>

        </div>

        <div class="form-group">

            @Html.Label("Tuổi", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.EditorFor(model => model.Age)

            </div>

        </div>

        <div class="form-group">

            @Html.Label("Email", new { @class = "control-label col-md-2" })

            <div class="col-md-10">

                @Html.EditorFor(model => model.Email)

            </div>

        </div>

        <div class="form-group">

            <div class="col-md-offset-2 col-md-10">

                <input type="submit" value=" Lưu " class="btn btn-default" />

            </div>

        </div>

    </div>

}

Nvd.lab5.1/Views/NvdMember/Details.cshtml
@model Nvd.lab5._1.Models.NvdMember

@{
    ViewBag.Title = "Chi tiết thành viên";
}

<h2>Chi tiết thành viên</h2>

<div>
    <h4>NvdMember</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>

            Mã số

        </dt>



        <dd>

            @Html.DisplayFor(model => model.Id)

        </dd>

        <dt>

            Tên đăng nhập

        </dt>

        <dd>

            @Html.DisplayFor(model => model.Username)

        </dd>



        <dt>

            Họ và tên

        </dt>

        <dd>

            @Html.DisplayFor(model => model.FullName)

        </dd>

        <dt>

            Mật khẩu

        </dt>

        <dd>

            @Html.DisplayFor(model => model.Password)

        </dd>

        <dt>

            Tuổi

        </dt>

        <dd>

            @Html.DisplayFor(model => model.Age)

        </dd>

        <dt>

            Email

        </dt>

        <dd>

            @Html.DisplayFor(model => model.Email)

        </dd>

    </dl>

</div>

<p>

    @Html.ActionLink("Quay lại", "CreateOne")

</p>

Nvd.lab5.1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Nguyễn Văn Được</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nguyễn Văn Được", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Sử dụng HTML5 validate", "CreateOne", "NvdMember", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Tự validate", "CreateTwo", "NvdMember", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Sử dụng Annotation validate", "CreateThree", "NvdMember", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>