NVD_lession06/Models/NvdSong.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NVD_lession06.Models
{
    public class NvdSong
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Nvd: Hãy nhập tiêu đề")]
        [DisplayName("Tiêu đề")]
        public string NvdTitle { get; set; }
        [Required(ErrorMessage = "Nvd: Hãy nhập tác giả")]
        [DisplayName("Tác giả")]
        public string NvdAuThor {  get; set; }
        [Required(ErrorMessage = "Nvd: Hãy nhập nghệ sĩ")]
        [StringLength(50,MinimumLength =2,ErrorMessage ="Nvd: Tên nghệ sĩ có tối thiểu 2 ký tự, tối đa 50 ký tự")]
        [DisplayName("Nghệ sĩ")]
        public string NvdArtist { get; set;}
        [Required(ErrorMessage = "Nvd: Hãy nhập nhà xuất bản")]
        [RegularExpression(@"[0-9]{4}",ErrorMessage ="Nvd: Nhập xuất bản phải có 2 ký tự số")]
        [Range(1900,2024,ErrorMessage ="Nvd: Năm xuất bản trong khoảng 1900 - 2024")]
        [DisplayName("Năm xuất bản")]
        public int NvdYearRelease { get; set;}
    }
}

NVD_lession06/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NVD_lession06.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NVD_lession06/Controllers/NvdSongController.cs
using NVD_lession06.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NVD_lession06.Controllers
{
    public class NvdSongController : Controller
    {
        private static List<NvdSong> nvdSongs = new List<NvdSong>()
        {
            new NvdSong{Id=221090016,NvdTitle="Nguyễn Văn Được",NvdAuThor="K22CNT3",NvdArtist="NTU",NvdYearRelease=2024},
            new NvdSong{Id=1,NvdTitle="Phan Viết Vượng",NvdAuThor="K22CNT3",NvdArtist="NTU",NvdYearRelease=2024}
        };
        // GET: NvdSong
        /// <summary>
        /// Hiển thị danh sách bài hát
        /// Author: Nguyễn Văn Được
        /// </summary>
        /// <returns></returns>
        public ActionResult NvdIndex()
        {
            return View(nvdSongs);
        }
        //  GET: NvdCreate
        /// <summary>
        /// From thêm mới bài hát
        /// Author: Nguyễn Văn Được
        /// </summary>
        /// <returns></returns>
        public ActionResult NvdCreate()
        {
            var NvdSong = new NvdSong();
            return View();
        }
    }
}

NVD_lession06/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

NVD_lession06/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

NVD_lession06/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

NVD_lession06/Views/NvdSong/NvdCreate.cshtml
@model NVD_lession06.Models.NvdSong

@{
    ViewBag.Title = "NvdCreate: Thêm mới bài hát";
}

<h2>NvdCreate - Thêm mới bài hát</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NvdTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvdTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvdTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvdAuThor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvdAuThor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvdAuThor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvdArtist, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvdArtist, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvdArtist, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvdYearRelease, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvdYearRelease, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvdYearRelease, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" name="btnNvd" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NVD_lession06/Views/NvdSong/NvdIndex.cshtml
@model IEnumerable<NVD_lession06.Models.NvdSong>

@{
    ViewBag.Title = "Nvd: Danh sách bài hát";
}

<h2>Nvd: Danh sách bài hát</h2>

<p>
    @Html.ActionLink("Create New", "NvdCreate")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NvdTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NvdAuThor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NvdArtist)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NvdYearRelease)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NvdTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NvdAuThor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NvdArtist)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NvdYearRelease)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

NVD_lession06/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Nguyễn Văn Được</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nguyễn Văn Được", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Nvd: Danh sách Song", "NvdIndex", "NvdSong", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>